/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject2.swing;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.concurrent.TimeUnit;
import javax.swing.JFrame;
/**
 *
 * @author wahin
 */
public class UserWindow extends javax.swing.JFrame {

    /**
     * Creates new form UserWindow
     */
    
    public UserWindow(String username) {
        user = username;
        getData(user);
    //    FillCombo();
        initComponents(); 
    }
    
    public void getData(String username)
    {
        try {
            Database db =  new Database("jdbc:mysql://localhost:3306/mydb?useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata");
            this.rs = db.get_user_data(username);
            rs.next();
         //   db.con.close();
        } catch (Exception ex) {
          Logger.getLogger(UserWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        Main = new javax.swing.JPanel();
        book = new javax.swing.JButton();
        checkbalance = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        BookCab = new javax.swing.JPanel();
        start = new javax.swing.JComboBox<>();
        hatchback = new javax.swing.JRadioButton();
        end = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        BookNow = new javax.swing.JButton();
        sedan = new javax.swing.JRadioButton();
        SUV = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bill = new javax.swing.JButton();
        CheckBal = new javax.swing.JPanel();
        AddMoney = new javax.swing.JButton();
        addedBal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        AfterBook = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        billstart = new javax.swing.JLabel();
        billend = new javax.swing.JLabel();
        billprice = new javax.swing.JLabel();
        billdriver = new javax.swing.JLabel();
        billcarnum = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        rating = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        billtime = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        buttonGroup1.add(hatchback);
        buttonGroup1.add(SUV);
        buttonGroup1.add(sedan);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(76, 185, 218));
        setSize(new java.awt.Dimension(900, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main.setBackground(new java.awt.Color(140, 209, 234));
        Main.setPreferredSize(new java.awt.Dimension(900, 440));

        book.setBackground(new java.awt.Color(218, 239, 255));
        book.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        book.setText("Book A Cab");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        checkbalance.setBackground(new java.awt.Color(218, 239, 255));
        checkbalance.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        checkbalance.setText("Wallet");
        checkbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbalanceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Welcome");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText(user);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\wahin\\Pictures\\bar.png")); // NOI18N
        jLabel18.setText("jLabel18");

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\wahin\\Pictures\\small2.png")); // NOI18N
        jLabel19.setText("jLabel19");

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\wahin\\Pictures\\21-512.png")); // NOI18N

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkbalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(177, 177, 177)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(MainLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelSlider1.add(Main, "card2");

        BookCab.setBackground(new java.awt.Color(140, 209, 234));

        start.setBackground(new java.awt.Color(46, 46, 46));
        start.setFont(new java.awt.Font("Amiri", 1, 14)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 242));
        start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thumkunta", "Secunderabad Railway Station", "Bits Hyderabad Main Gate", "Nampally", "Parade Ground", "Hyderabad Cricket Stadium", "Shameerpet", "Ameerpet", "Uppal", "BegumPet" }));

        hatchback.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        hatchback.setText("Hatchback");

        end.setBackground(new java.awt.Color(46, 46, 46));
        end.setFont(new java.awt.Font("Amiri", 1, 14)); // NOI18N
        end.setForeground(new java.awt.Color(255, 255, 242));
        end.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thumkunta", "Secunderabad Railway Station", "Bits Hyderabad Main Gate", "Nampally", "Parade Ground", "Hyderabad Cricket Stadium", "Shameerpet", "Ameerpet", "Uppal", "BegumPet" }));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Amiri", 1, 14)); // NOI18N
        jButton4.setText("Check Fare");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BookNow.setBackground(new java.awt.Color(153, 153, 153));
        BookNow.setFont(new java.awt.Font("Amiri", 1, 14)); // NOI18N
        BookNow.setText("Book Now");
        BookNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookNowActionPerformed(evt);
            }
        });

        sedan.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        sedan.setText("Sedan");

        SUV.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        SUV.setText("SUV");

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("Amiri", 1, 14)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("Select Car type:");

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel13.setText("Your location :");

        jLabel14.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel14.setText("Choose Destination :");

        bill.setBackground(new java.awt.Color(153, 153, 153));
        bill.setFont(new java.awt.Font("Amiri", 1, 14)); // NOI18N
        bill.setText("Bill");
        bill.setVisible(false);
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BookCabLayout = new javax.swing.GroupLayout(BookCab);
        BookCab.setLayout(BookCabLayout);
        BookCabLayout.setHorizontalGroup(
            BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookCabLayout.createSequentialGroup()
                .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookCabLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SUV, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hatchback, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sedan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(BookCabLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BookCabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BookCabLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(49, 49, 49))
                            .addGroup(BookCabLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(end, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(start, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))
                    .addGroup(BookCabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(BookNow, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        BookCabLayout.setVerticalGroup(
            BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookCabLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookCabLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(BookCabLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(sedan)))
                .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookCabLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(BookCabLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(SUV)))
                .addGap(25, 25, 25)
                .addComponent(hatchback, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(BookCabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookNow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        jPanelSlider1.add(BookCab, "card3");

        CheckBal.setBackground(new java.awt.Color(140, 209, 234));

        AddMoney.setBackground(new java.awt.Color(153, 153, 153));
        AddMoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddMoney.setText("Add Money");
        AddMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMoneyActionPerformed(evt);
            }
        });

        addedBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addedBalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Amiri", 1, 24)); // NOI18N
        jLabel5.setText("Enter amount :");

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Check Balance");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Amiri", 1, 36)); // NOI18N
        jLabel15.setText("Wallet");

        javax.swing.GroupLayout CheckBalLayout = new javax.swing.GroupLayout(CheckBal);
        CheckBal.setLayout(CheckBalLayout);
        CheckBalLayout.setHorizontalGroup(
            CheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckBalLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckBalLayout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(CheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckBalLayout.createSequentialGroup()
                        .addComponent(AddMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckBalLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckBalLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(addedBal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))))
        );
        CheckBalLayout.setVerticalGroup(
            CheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckBalLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel15)
                .addGap(90, 90, 90)
                .addGroup(CheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addedBal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(AddMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(CheckBalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jPanelSlider1.add(CheckBal, "card4");

        AfterBook.setBackground(new java.awt.Color(140, 209, 234));

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        back.setText("<- Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        jLabel3.setText("Start");

        jLabel4.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        jLabel4.setText("End");

        jLabel6.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        jLabel6.setText("Price");

        jLabel7.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        jLabel7.setText("Driver");

        jLabel8.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        jLabel8.setText("Car Number");

        billstart.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        billstart.setText("jLabel9");

        billend.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        billend.setText("jLabel10");

        billprice.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        billprice.setText("jLabel11");

        billdriver.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        billdriver.setText("jLabel12");

        billcarnum.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        billcarnum.setText("jLabel13");

        jLabel9.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        jLabel9.setText("Contact No");

        jLabel10.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        jLabel10.setText("1800-2400-1111");

        jLabel16.setFont(new java.awt.Font("Amiri", 1, 24)); // NOI18N
        jLabel16.setText("Ride Details");

        confirm.setBackground(new java.awt.Color(153, 153, 153));
        confirm.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        jLabel17.setText("Rating");

        rating.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        rating.setText("jLabel19");

        jLabel11.setFont(new java.awt.Font("Amiri", 1, 18)); // NOI18N
        jLabel11.setText("Time Required");

        billtime.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        billtime.setText("jLabel19");

        jLabel20.setFont(new java.awt.Font("Amiri", 0, 18)); // NOI18N
        jLabel20.setText("min");

        javax.swing.GroupLayout AfterBookLayout = new javax.swing.GroupLayout(AfterBook);
        AfterBook.setLayout(AfterBookLayout);
        AfterBookLayout.setHorizontalGroup(
            AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterBookLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(349, Short.MAX_VALUE))
            .addGroup(AfterBookLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AfterBookLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billstart, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AfterBookLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(billdriver, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billend, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(AfterBookLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AfterBookLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(AfterBookLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AfterBookLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(78, 78, 78)
                                .addComponent(billtime, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AfterBookLayout.createSequentialGroup()
                                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AfterBookLayout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(billcarnum, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(billprice, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(AfterBookLayout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        AfterBookLayout.setVerticalGroup(
            AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AfterBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billstart, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billdriver)
                    .addComponent(jLabel17)
                    .addComponent(rating, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AfterBookLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(billprice)
                        .addGap(26, 26, 26)
                        .addComponent(billcarnum)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AfterBookLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(billtime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(11, 11, 11)
                        .addGroup(AfterBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanelSlider1.add(AfterBook, "card5");

        getContentPane().add(jPanelSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
              jPanelSlider1.nextPanel(10,BookCab,jPanelSlider1.left);
    }//GEN-LAST:event_bookActionPerformed

    private void checkbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbalanceActionPerformed
        // TODO add your handling code here:
        jPanelSlider1.nextPanel(10,CheckBal,jPanelSlider1.right);
    }//GEN-LAST:event_checkbalanceActionPerformed

    private void AddMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMoneyActionPerformed
        try{
        int money = Integer.parseInt(addedBal.getText()); // Logger.getLogger(UserWindow.class.getName()).log(Level.SEVERE, null, ex);
        if(money>0&&money<=10000)
        {
            Database db = new Database("jdbc:mysql://localhost:3306/mydb?useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata");
            db.updateBal(user,money,db.getBal(user));
            javax.swing.JOptionPane.showMessageDialog(null,"Successfully added ");
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Please enter between 1 to 10000");
        }
        }
        catch(Exception e)
                {
                    javax.swing.JOptionPane.showMessageDialog(null,"Please enter an Integer");
                }
    }//GEN-LAST:event_AddMoneyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Database db = new Database("jdbc:mysql://localhost:3306/mydb?useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata");
        int bal = db.getBal(user);
        javax.swing.JOptionPane.showMessageDialog(null,"Your current balance is "+ bal);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addedBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addedBalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addedBalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           jPanelSlider1.nextPanel(10,Main,jPanelSlider1.left);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         if(!start.getSelectedItem().toString().equals(end.getSelectedItem().toString()))
                 {
                     String start_loc =start.getSelectedItem().toString();
                     String end_loc = end.getSelectedItem().toString();
                     int type = getRadioButton();
                     if(type!=0)
                     {javax.swing.JOptionPane.showMessageDialog(null,"Price is "+Location.get_price(start_loc, end_loc, type));}
                     else
                     {
                         javax.swing.JOptionPane.showMessageDialog(null,"Please select a cab type");
                     }
                 }
         else
         {
             javax.swing.JOptionPane.showMessageDialog(null,"Please select different locations");
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPanelSlider1.nextPanel(10,Main,jPanelSlider1.right);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void BookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNowActionPerformed
        String start_loc =start.getSelectedItem().toString();
        String end_loc = end.getSelectedItem().toString();
        int type = getRadioButton();
        int fare =Location.get_price(start_loc, end_loc, type);
        Database db = new Database("jdbc:mysql://localhost:3306/mydb?useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata");
        ResultSet highRating = db.isAvailable(type, start_loc);
        if(!db.isInCab(user)){
        if(!Booking.sameloc(start_loc, end_loc))
        {
            if(Booking.checkSufficientBalance(user,Location.get_price(start_loc, end_loc, type)))
            {
                try {
                    
                    if(highRating!=null&&highRating.next())
                    {
                    confirm.setVisible(true);
                    String carnum = highRating.getString("CarNum");
               //     setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
                    System.out.println(fare*-1);
                    billprice.setText(Integer.toString(fare));
                    billstart.setText(start_loc);
                    billend.setText(end_loc);
                    billcarnum.setText(highRating.getString("CarNum"));
                    billdriver.setText(highRating.getString("Name"));
                    rating.setText(Double.toString(highRating.getDouble("Rating")));
                    Random r = new Random();
                    billtime.setText(Integer.toString(17+r.nextInt(8)));
                    //db.updateBal(user,-1*fare,db.getCurrBal(user));
                    //db.fromxtoy(start_loc,end_loc, carnum);
                    //db.changeStatus(carnum,1);
                    //db.changeStatusStudent(user, 1);
                    //Booking.rides++;
                    //Booking.redistribute();
                    jPanelSlider1.nextPanel(10,AfterBook,jPanelSlider1.left);
                    //setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                    //Background.startThread(carnum, user,this);
                 //   db.changeStatus(carnum,0);
                      //  startThread(carnum);
                    }
                    else {
                        javax.swing.JOptionPane.showMessageDialog(null,"Selected Car type is unavailable Please Select a different car type");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(UserWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Insufficient Balance");
            }
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Please chose different location");
        }
        } else
        {
            javax.swing.JOptionPane.showMessageDialog(null,"You are already in a cab");
        }
    }//GEN-LAST:event_BookNowActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        jPanelSlider1.nextPanel(10,BookCab,jPanelSlider1.right);
    }//GEN-LAST:event_backActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        
        try {
            confirm.setVisible(false);
            String start_loc = billstart.getText();
            String end_loc = billend.getText();
            int type = getRadioButton();
            int fare = Integer.parseInt(billprice.getText());
            String carnum = billcarnum.getText();
            Database db = new Database("jdbc:mysql://localhost:3306/mydb?useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata");
            ResultSet highRating = db.isAvailable(type, start_loc);
            if(highRating!=null&&highRating.next()&&highRating.getString("CarNum").equals(carnum))
            {
                db.updateBal(user,-1*fare,db.getCurrBal(user));
                db.fromxtoy(start_loc,end_loc, carnum);
                db.changeStatus(carnum,1);
                db.changeStatusStudent(user, 1);
                bill.setVisible(true);
                Booking.rides++;
                Booking.redistribute();
                setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                javax.swing.JOptionPane.showMessageDialog(null,"Booking Successful");
                Background.startThread(carnum, user,this);
            }
            else
            {
                javax.swing.JOptionPane.showMessageDialog(null,"Booking unsuccessful");
            }
        } catch (SQLException ex) {
         //   Logger.getLogger(UserWindow.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(null,"Booking unsuccessful");
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        jPanelSlider1.nextPanel(10,AfterBook,jPanelSlider1.right);
    }//GEN-LAST:event_billActionPerformed
    public int getRadioButton()
    {

        if (hatchback.isSelected() == true) return 2;
        if (sedan.isSelected() == true) return 4;
        if (SUV.isSelected() == true) return 5;
        return 0;
    }
   /*  public void startThread(String carnum)
    {
        SwingWorker sw = new SwingWorker()
        {
            @Override
            protected String doInBackground() throws Exception
            {
                Thread.sleep(10000);
                Database db = new Database("jdbc:mysql://localhost:3306/mydb?useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata");
                db.changeStatus(carnum,0);
                db.changeStatusStudent(user,0);
                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                return "done";
            }
        };
        sw.execute();
    }*/
   /*public void FillCombo()
    {
        try {
            Database db2 = new Database("jdbc:mysql://localhost:3306/mydb?useLegacyDatetimeCode=false&serverTimezone=Asia/Kolkata");
            ResultSet rs1 = db2.getLoc();
            while(rs1.next())
            {
                String name =rs1.getString("Locations");
                System.out.println(name);
                if(rs1==null)
                {
                    System.out.println("hello");
                }
                start.addItem(name);
                end.addItem(name);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(UserWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }*/
  /*  public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserWindow().setVisible(true);
            }
        });
    }*/
    /**
     * @param args the command line arguments
     */
    private String user;
    private ResultSet rs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMoney;
    private javax.swing.JPanel AfterBook;
    private javax.swing.JPanel BookCab;
    private javax.swing.JButton BookNow;
    private javax.swing.JPanel CheckBal;
    private javax.swing.JPanel Main;
    private javax.swing.JRadioButton SUV;
    private javax.swing.JTextField addedBal;
    private javax.swing.JButton back;
    public javax.swing.JButton bill;
    private javax.swing.JLabel billcarnum;
    private javax.swing.JLabel billdriver;
    private javax.swing.JLabel billend;
    private javax.swing.JLabel billprice;
    private javax.swing.JLabel billstart;
    private javax.swing.JLabel billtime;
    private javax.swing.JButton book;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checkbalance;
    private javax.swing.JButton confirm;
    private javax.swing.JComboBox<String> end;
    private javax.swing.JRadioButton hatchback;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JLabel rating;
    private javax.swing.JRadioButton sedan;
    private javax.swing.JComboBox<String> start;
    // End of variables declaration//GEN-END:variables
}
